spring.application.name=ms-pedidos-360-catalog
server.port=8081
# Conexión a Oracle Autonomous DB usando la Wallet
spring.datasource.url=jdbc:oracle:thin:@gcn5ldacwb15oubf_tp
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=/home/theicedk/Escritorio/2026/Cloud Native/proyecto_backend_pedidos360/Pedidos360Backend/Wallet_pedidos360db
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=(SOURCE=(METHOD=FILE)(METHOD_DATA=(DIRECTORY=/home/theicedk/Escritorio/2026/Cloud Native/proyecto_backend_pedidos360/Pedidos360Backend/Wallet_pedidos360db)))
spring.datasource.username=ADMIN
spring.datasource.password=Pedidos360Database
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuración Hibernate / JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Configuración JWT (Microsoft Entra ID)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/8dd4fb88-ff26-4101-a3ff-9c3b46315bd3/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=0ab8451e-f1ac-4ca0-995c-5557ce2e3893

