spring.application.name=ms-pedidos-360-bff
server.port=8080

# Issuer v2.0 del Tenant de Microsoft Entra ID
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/8dd4fb88-ff26-4101-a3ff-9c3b46315bd3/v2.0

# Application (client) ID de la App Registration del Backend/API
spring.security.oauth2.resourceserver.jwt.audiences=0ab8451e-f1ac-4ca0-995c-5557ce2e3893

# URLs internas de los microservicios de dominio
services.catalog.url=http://localhost:8081
services.orders.url=http://localhost:8082